
const CrawlerData = require('./crawlerData')
const CrawlerFactory = require('./crawlerDataFactory')
// const Factory = new CrawlerData()
// console.log('CrawlerFactory.BASE_URL', CrawlerFactory.BASE_URL)
// console.log('CrawlerFactory.setBASE_URL("vaiii")', CrawlerFactory.setBASE_URL(CrawlerData.BASE_URL))
// console.log('CrawlerFactory.getBASE_URL', CrawlerFactory.getBASE_URL())
CrawlerFactory.setBASE_URL(CrawlerData.BASE_URL)
CrawlerFactory.setElementList(CrawlerData.ElementList)
CrawlerFactory.setFieldValueType(CrawlerData.FieldValueType)
CrawlerFactory.setFields(CrawlerData.Fields)
CrawlerFactory.setOptionsRequest(CrawlerData.optionsRequest)
CrawlerFactory.setOptions(CrawlerData.options)
CrawlerFactory.setPROMISE_SUCCESS(CrawlerData.PROMISE_SUCCESS)
CrawlerFactory.setPROMISE_ERROR(CrawlerData.PROMISE_ERROR)
CrawlerFactory.setcallback(CrawlerData.callback)

module.exports = CrawlerFactory.getCrawler()